[build.env]
passthrough = ["OPENSSL_NO_VENDOR", "OPENSSL_INCLUDE_DIR", "OPENSSL_LIB_DIR"]

[target.aarch64-unknown-linux-gnu]
pre-build = [
  "dpkg --add-architecture arm64 || true",
  "apt-get update",
  "apt-get install -y libssl-dev libssl-dev:arm64 perl"
]
